# Generated by Django 4.1.2 on 2022-10-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comentarios', '0002_remove_comentario_nome_comentario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='titulo_comentario',
        ),
        migrations.AddField(
            model_name='comentario',
            name='nome_comentario',
            field=models.CharField(default='Padrão', max_length=255, verbose_name='Titulo'),
        ),
    ]
