# Generated by Django 4.1.2 on 2022-10-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='id_categoria',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome_categoria',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome'),
        ),
    ]
